print("What do you call a fake noodle?")
input()
print("An impasta!!")
input("-------------------------------")
print("What do you call a magic dog?")
input()
print("A labracadabrador!!")
input("-------------------------------")
print("How did the picture go to prison?")
input()
print("It got framed!!")
input("-------------------------------")
print("How many tickles does it take to make an octopus laugh?")
input()
print("Ten-tickles!!")
input("-------------------------------")
print("Why do we tell actors to “break a leg”?")
input()
print("Because every play has a cast!!")
input("-------------------------------")