name = input("What is your name? ")
print("")
print(" _   _      _ _ ")      
print("| | | |    | | |   ")   
print("| |_| | ___| | | ___  ")
print("|  _  |/ _ \ | |/ _ \ ")
print("| | | |  __/ | | (_) |")
print("\_| |_/\___|_|_|\___/ ")
print(f"Hello {name}! Welcome to Ct8!")
print("Today we will tell a story with your help")
print("")
location = input("Pick a location starting with the: ")
friend = input("Pick a name: ")
activity = input("Pick a activity: ")
animal = input("Pick a animal: ")
adjective = input("Pick an adjective: ")
object = input("Pick a object: ")
building = input("Pick a building: ")
food = input("Pick a food: ")
location2 = input("Pick another location: ")
action = input("Pick a past tense action: ")
ingredient = input("Pick an ingredient: ")
ingredient2 = input("Pick another ingredient: ")
kitchen_appliance = input("Pick a kitchen appliance: ")
descriptive_word = input("Pick another adjective: ")
number = input("Pick a number: ")
action2 = input("Pick another past tense action: ")

input("--------------------------------------------------------------------")
print(f"{name} and {friend} are going to {location}.")
print(f"When they got there, {friend} found a {adjective} {animal} hiding behind a {object}.")
print(f"They decide to take the {animal} to a {building}.")
print(f"When they get there with the {adjective} {animal}, they realized that they became very hungry for {food}.")
print(f"So they decided to go to the {location2} to make it.")
print(f"They {action} to {location2}.")
print(f"First {friend} grabbed the {ingredient} and added it to a bowl.")
print(f"Next {name} grabbed {ingredient2} and gave it to {friend} to add to the bowl.")
print(f"Then they brought it over to the {kitchen_appliance} and cooked it in there.")
print(f"After {number} minutes, {name} took it out of the {kitchen_appliance}.")
print(f"As {friend} and {name} {action2}, they ate their {descriptive_word} {food} with the {animal}.") 
print(f"The End!")